spring:
  application:
    name: auth-service

  data:
    mongodb:
      #      uri: mongodb://localhost:27017/auth-service
      authentication-database: admin
      database: auth
      host: localhost
      port: 27017

  config:
    import: configserver:http://localhost:8888