server:
  port: 8084

spring:
  data:
    mongodb:
#      uri: mongodb://localhost:27017/auth-service
      authentication-database: admin
      database: auth-service
      host: localhost
      port: 27017


#  security:
#    user:
#      name: user
#      password: password
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:9090/auth/realms/spring-boot-keycloak
#          jwk-set-uri: http://localhost:9090/auth/realms/spring-boot-keycloak/protocol/openid-connect/certs
#          audience: account
